config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :users
	root to: 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates_presence_of :title, :text
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :registerable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,  :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  def index
    @articles = Article.all
    # add in later w/ will_paginate: .paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "The article was created succesfully." }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "The article was updated succesfully." }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to airticles_url, notice: "The article was succesfully deleted." }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow trusted parameters
    def article_params
      params.require(:article).permit(:title, :text, :slug, :description, :published)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@articles = Article.all
	end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:make, :model, :year, :price, :for_sale, :interior_color, :exterior_color, :craigslist_url, :website_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/articles/_articles.html.erb
<h1><%= icon('newspaper-o') %> Devon Kiss Studio's Articles</h1>
<hr>

<div class="media is-fullwidth">
	<div class="media-body">
		<% @articles.each do |article| %>
			<h3 class="article__title"><%= article.title %></h3>

			<div>
					<span class="tag is-light date">PUBLISHED <%= article.created_at.strftime('%m/%d/%Y') %></span>
			</div>

				<%= article.text %>

			<br /><br />
		<% end %>

		<hr />
		<% if user_signed_in? %>
		<button class="button is-medium">
			<%= link_to icon('newspaper-o')+' Create New Article', new_article_path %>
		</button>
		<% else %>
		<button class="button is-medium">
			<%= link_to icon('sign-in')+' Sign In', new_user_session_path %>
		</button>
		<% end %>
	</div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Title"  %>
    <%= form.text_field :title, id: :title, class: "input is-medium" %>
  </div>

  <br>

  <div class="field">
    <%= form.label "Text"  %>
    <%= form.text_area :text, id: :text, class: "textarea is-medium" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Publish Article", class: "button is-medium" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h2>Edit Article</h2>
<hr>
<%= render('form') %>

app/views/articles/index.html.erb
<h1><%= icon('leaf') %> Articles</h1>
<hr>

<div class="media is-fullwidth">
	<div class="media-body">
		<table class="table table-hover">
			<thead>
				<tr>
					<th>ID</th>
					<th>Title</th>
					<th>Slug</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @articles.each do |article| %>
				<tr>
					<td><%= article.id %></td>
					<td><%= article.title %> </td>
					<td><%= article.slug %> </td>
					<td><%= link_to 'Show', article, class: 'btn btn-sm btn-default' %></td>
	        <td><%= link_to 'Edit', edit_article_path(article), class: 'btn btn-sm btn-success' %></td>
	        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<%= link_to icon('leaf')+' Create New Article', new_article_path, class: "" %>
	</div>
</div>

app/views/articles/new.html.erb
<h2><%= icon('newspaper-o') %> Create an Article</h2>
<%= render('form') %>
<br>
<%= link_to 'Back', articles_path, class: "button is-link" %>

app/views/articles/show.html.erb
<h1 class="article__title"><%= @article.title %></h1>
<hr>
<p class="date">
	PUBLISHED <%= @article.created_at.strftime('%m/%d/%Y') %>
</p>
<br>

	<%= @article.text %>

<hr>

<%= link_to 'Edit', edit_article_path(@article), class: "button is-rounded" %>
<%= link_to 'Back', articles_path, class: "button is-rounded" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articles by Devon Kiss Studios</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <%= render('shared/nav') %>
    <%= render('shared/alerts') %>

  	<div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/index.html.erb
<%= render('articles/articles') %>

app/views/shared/_alerts.html.erb
<% if notice || alert %>
	<div class="notification is-info">
		<button class="delete" onClick="closeNotification();"></button>
			<% if notice %>
				<p class="notice"><%= notice %></p>
			<% end %>

			<% if alert %>
				<p class="alert"><%= alert %></p>
			<% end %>
	</div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar is-transparent">
  <div class="navbar-brand">
     <%= link_to "DEVON KISS STUDIO'S ARTICLES", root_path, class: "navbar-item" %>
    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item" %>
      <%= link_to "Articles", articles_path, class: "navbar-item" %>
			<% if user_signed_in? %>
			  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-item" %>
			<% else %>
				<%= link_to "Log In", new_user_session_path, class: "navbar-item" %>
			<% end %>
    </div>
		<%= render('shared/navbar-dropdown') %>
    <%= render('shared/navbar-end') %>
  </div>
</nav>

app/views/shared/_navbar-dropdown.html.erb
<!-- <div class="navbar-item has-dropdown is-hoverable">
  <a class="navbar-link" href="/documentation/overview/start/">
    Docs
  </a>
  <div class="navbar-dropdown is-boxed">
    <a class="navbar-item" href="/documentation/overview/start/">
      Overview
    </a>
    <a class="navbar-item" href="https://bulma.io/documentation/modifiers/syntax/">
      Modifiers
    </a>
    <a class="navbar-item" href="https://bulma.io/documentation/columns/basics/">
      Columns
    </a>
    <a class="navbar-item" href="https://bulma.io/documentation/layout/container/">
      Layout
    </a>
    <a class="navbar-item" href="https://bulma.io/documentation/form/general/">
      Form
    </a>
    <hr class="navbar-divider">
    <a class="navbar-item" href="https://bulma.io/documentation/elements/box/">
      Elements
    </a>
    <a class="navbar-item is-active" href="https://bulma.io/documentation/components/breadcrumb/">
      Components
    </a>
  </div>
</div> -->

app/views/shared/_navbar-end.html.erb
<!-- <div class="navbar-end">
  <div class="navbar-item">
    <div class="field is-grouped">
      <p class="control">
        <a class="bd-tw-button button" data-social-network="Twitter" data-social-action="tweet" data-social-target="http://localhost:4000" target="_blank" href="https://twitter.com/intent/tweet?text=Bulma: a modern CSS framework based on Flexbox&amp;hashtags=bulmaio&amp;url=http://localhost:4000&amp;via=jgthms">
          <span class="icon">
            <i class="fa fa-twitter"></i>
          </span>
          <span>
            Tweet
          </span>
        </a>
      </p>
      <p class="control">
        <a class="button is-primary" href="https://github.com/jgthms/bulma/archive/0.5.1.zip">
          <span class="icon">
            <i class="fa fa-download"></i>
          </span>
          <span>Download</span>
        </a>
      </p>
    </div>
  </div>
</div> -->

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make, id: :vehicle_make %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :vehicle_model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :vehicle_year %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :vehicle_price %>
  </div>

  <div class="field">
    <%= form.label :for_sale %>
    <%= form.check_box :for_sale, id: :vehicle_for_sale %>
  </div>

  <div class="field">
    <%= form.label :interior_color %>
    <%= form.text_field :interior_color, id: :vehicle_interior_color %>
  </div>

  <div class="field">
    <%= form.label :exterior_color %>
    <%= form.text_field :exterior_color, id: :vehicle_exterior_color %>
  </div>

  <div class="field">
    <%= form.label :craigslist_url %>
    <%= form.text_field :craigslist_url, id: :vehicle_craigslist_url %>
  </div>

  <div class="field">
    <%= form.label :website_url %>
    <%= form.text_field :website_url, id: :vehicle_website_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Price</th>
      <th>For sale</th>
      <th>Interior color</th>
      <th>Exterior color</th>
      <th>Craigslist url</th>
      <th>Website url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.price %></td>
        <td><%= vehicle.for_sale %></td>
        <td><%= vehicle.interior_color %></td>
        <td><%= vehicle.exterior_color %></td>
        <td><%= vehicle.craigslist_url %></td>
        <td><%= vehicle.website_url %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @vehicle.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Price:</strong>
  <%= @vehicle.price %>
</p>

<p>
  <strong>For sale:</strong>
  <%= @vehicle.for_sale %>
</p>

<p>
  <strong>Interior color:</strong>
  <%= @vehicle.interior_color %>
</p>

<p>
  <strong>Exterior color:</strong>
  <%= @vehicle.exterior_color %>
</p>

<p>
  <strong>Craigslist url:</strong>
  <%= @vehicle.craigslist_url %>
</p>

<p>
  <strong>Website url:</strong>
  <%= @vehicle.website_url %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>